const a = "" + 1 + 0;
console.log(a);
const b = "" - 1 + 0;
console.log(b);
const d = true + false;
console.log(d);
const e = true - false;
console.log(e);
const f = true / false;
console.log(f);
const g = "true" - false;
console.log(g);
const h = true + " false";
console.log(h);
const i = true * false;
console.log(i);
const j = true * 1000;
console.log(j);
const k = 1000 * false;
console.log(k);
const l = 6 / "3";
console.log(l);
const m = "6" / "2";
console.log(m);
const n = "6/n" + 2;
console.log(n);
const o = "6/n" - 2;
console.log(o);
const p = "2" * "3";
console.log(p);
const q = 4 + 5 + " px";
console.log(q);
const r = 4 / n + 5 + " px";
console.log(r);
const s = null + " px";
console.log(s);
const t = undefined + " px";
console.log(t);
const u = undefined - " px";
console.log(u);
const v = null - " px";
console.log(v);
const w = true + " px";
console.log(w);
const x = true + " 2";
console.log(x);
const y = true - "2";
console.log(y);
const z = false - "2";
console.log(z);
const aa = true + 2;
console.log(aa);
const bb = false + 2;
console.log(bb);
const cc = true * 2;
console.log(cc);
const dd = false * 2;
console.log(dd);
const ee = 2 / 0 + " 0 / 2";
console.log(ee);
const ff = 2 / 0 - " 0 / 2";
console.log(ff);
const gg = "4" - 2;
console.log(gg);
const hh = "4/n" - 2;
console.log(hh);
const ii = "4px" - 2;
console.log(ii);
const jj = "4px " + 2;
console.log(jj);
const kk = "4px " - true + 2;
console.log(kk);
const ll = true + 2 + " 4px";
console.log(ll);
const mm = false / false; // NaN
console.log(mm);
const nn = false / true;
console.log(nn);
const oo = true / true;
console.log(oo);
const pp = 1000 / false;
console.log(pp);
const qq = 0 / 0;
console.log(qq); // NaN
const rr = false * false;
console.log(rr);
const ss = 7 / 0;
console.log(ss);
const tt = "  -9\n" + 5;
console.log(tt);
const uu = true + 5;
console.log(uu);
const ww = "  -9\n" - 5;
console.log(ww);
const xx = null + 1;
console.log(xx);
const yy = undefined + 1;
console.log(yy);
const zz = "undefined" + 1;
console.log(zz);
const aaa = "undefined" - 1;
console.log(aaa);
const bbb = "true" - "false";
console.log(bbb);
const ccc = "true" - 2;
console.log(ccc);
const ddd = 2 - "true";
console.log(ddd);
const eee = undefined + " true";
console.log(eee);
const fff = null + " true";
console.log(fff);
const ggg = 2 * 5 + " 2*5";
console.log(ggg);
const hhh = 2 * 5 - " 2*5";
console.log(hhh);
const iii = "25" - 2 * 5;
console.log(iii);
const jjj = null / true;
console.log(jjj);
const kkk = "" / true;
console.log(kkk);
const lll = 0 / true;
console.log(lll);
const mmm = undefined / true;
console.log(mmm);
const nnn = 0 / null;
console.log(nnn);
const ooo = null / 0;
console.log(ooo);
const ppp = null / false;
console.log(ppp);
const qqq = "" / false;
console.log(qqq);
const rrr = "" - true + false;
console.log(rrr);
const sss = true + false + "";
console.log(sss);
const ttt = true + false + " true";
console.log(ttt);
const uuu = true + false + true;
console.log(uuu);
const vvv = null + false + true;
console.log(vvv);
const www = null + 100;
console.log(www);
const xxx = null * 100;
console.log(xxx);
const yyy = null - 100;
console.log(yyy);
const zzz = undefined + undefined;
console.log(zzz);
const aaaa = undefined - undefined;
console.log(aaaa);
const bbbb = null - null;
console.log(bbbb);
const cccc = null + null;
console.log(cccc);
const dddd = null + null + " 2";
console.log(dddd);
const eeee = null + null - "2";
console.log(eeee);
const ffff = null + null - "1*2";
console.log(ffff);
const gggg = null + null + "1*2";
console.log(gggg);
const hhhh = undefined + null;
console.log(hhhh);
const iiii = "" + null;
console.log(iiii);
const jjjj = "" - null;
console.log(jjjj);
const kkkk = "" - true;
console.log(kkkk);
const llll = "" - false;
console.log(llll);
